"""Write per-category execution results into TEST-EXECUTION-TRACKING.csv.

Usage: python qa_update.py <category>   (rows defined below per category)
The CSV keeps the skill's header; rows are appended (example row removed on first write).
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

CSV = (
    Path(__file__).resolve().parents[1]
    / "docs"
    / "templates"
    / "TEST-EXECUTION-TRACKING.csv"
)
DATE = "2026-07-18"
WHO = "Kimi-QA"

HEADER = [
    "Test Case ID",
    "Category",
    "Priority",
    "Test Name",
    "Estimated Time (min)",
    "Prerequisites",
    "Status",
    "Result",
    "Bug ID",
    "Execution Date",
    "Executed By",
    "Notes",
    "Screenshot/Log",
]

ROWS = {
    "atoms": [
        (
            "TC-ATM-001",
            "Atoms",
            "P0",
            "math-sum 正常加法",
            "1",
            "import core.py",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "result=30.0",
            "",
        ),
        (
            "TC-ATM-002",
            "Atoms",
            "P1",
            "math-sum 缺省参数",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "result=0.0",
            "",
        ),
        (
            "TC-ATM-003",
            "Atoms",
            "P1",
            "math-sum 非法输入",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "error 捕获正常",
            "",
        ),
        (
            "TC-ATM-004",
            "Atoms",
            "P3",
            "math-sum inf 行为",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "记录：1e308+1e308 返回 Infinity 且 status=success，建议校验输入范围",
            "",
        ),
        (
            "TC-ATM-005",
            "Atoms",
            "P0",
            "string-split 正常拆分",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "parts/count 正确",
            "",
        ),
        (
            "TC-ATM-006",
            "Atoms",
            "P1",
            "string-split maxsplit",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "maxsplit=2 正确",
            "",
        ),
        (
            "TC-ATM-007",
            "Atoms",
            "P2",
            "string-split 空分隔符",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "empty separator 被捕获",
            "",
        ),
        (
            "TC-ATM-008",
            "Atoms",
            "P0",
            "file-read 正常读取",
            "2",
            "临时文件",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "content/size 正确",
            "",
        ),
        (
            "TC-ATM-009",
            "Atoms",
            "P1",
            "file-read 文件不存在",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "file not found",
            "",
        ),
        (
            "TC-ATM-010",
            "Atoms",
            "P1",
            "file-read 超 max_size",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "file too large",
            "",
        ),
        (
            "TC-ATM-011",
            "Atoms",
            "P1",
            "file-read base64 模式",
            "2",
            "二进制文件",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "base64 往返一致",
            "",
        ),
        (
            "TC-ATM-012",
            "Atoms",
            "P1",
            "file-read 缺 path",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "missing required field: path",
            "",
        ),
        (
            "TC-ATM-013",
            "Atoms",
            "P0",
            "http-get 正常 GET",
            "3",
            "本地回环靶机",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "200 + 内容正确",
            "",
        ),
        (
            "TC-ATM-014",
            "Atoms",
            "P1",
            "http-get 缺 url",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "missing required field: url",
            "",
        ),
        (
            "TC-ATM-015",
            "Atoms",
            "P2",
            "http-get max_length 截断",
            "2",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "5000B 截断为 100B",
            "",
        ),
        (
            "TC-ATM-016",
            "Atoms",
            "P1",
            "http-get 无效 URL 容错",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "error 捕获正常",
            "",
        ),
        (
            "TC-ATM-017",
            "Atoms",
            "P1",
            "示例原子端口冲突",
            "2",
            "静态检查 server.py",
            "Completed",
            "Fail",
            "BUG-005",
            DATE,
            WHO,
            "5 个原子全部硬编码 0.0.0.0:8080，无法同时启动",
            "",
        ),
        (
            "TC-ATM-018",
            "Atoms",
            "P2",
            "meta id 规范一致性",
            "2",
            "静态检查",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "atom.file.read 等格式可过校验，但与 com.example.* 反向域名惯例不一致（建议项）",
            "",
        ),
    ],
    "registry": [
        (
            "TC-REG-001",
            "Registry",
            "P0",
            "提交新原子",
            "2",
            "临时 sqlite",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "submitted + 32 位 signature",
            "",
        ),
        (
            "TC-REG-002",
            "Registry",
            "P0",
            "重复 signature 不同 atom_id",
            "3",
            "同能力不同 id",
            "Completed",
            "Fail",
            "BUG-006",
            DATE,
            WHO,
            "签名载荷包含 atom_id，同能力不同 id 永不冲突，duplicate_signature 检查成死代码",
            "",
        ),
        (
            "TC-REG-003",
            "Registry",
            "P1",
            "同 id 重复提交=更新",
            "2",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "description 更新，submit 审计 2 条",
            "",
        ),
        (
            "TC-REG-004",
            "Registry",
            "P0",
            "审核通过 registered",
            "2",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "review_score=9 落库",
            "",
        ),
        (
            "TC-REG-005",
            "Registry",
            "P1",
            "审核拒绝 rejected",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "",
            "",
        ),
        (
            "TC-REG-006",
            "Registry",
            "P1",
            "审核不存在原子",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "not_found",
            "",
        ),
        (
            "TC-REG-007",
            "Registry",
            "P0",
            "registered→running",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "",
            "",
        ),
        (
            "TC-REG-008",
            "Registry",
            "P1",
            "submitted→running 非法",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "invalid_transition 拦截正确",
            "",
        ),
        (
            "TC-REG-009",
            "Registry",
            "P1",
            "list_atoms 状态过滤",
            "2",
            "3 状态各一",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "过滤准确",
            "",
        ),
        (
            "TC-REG-010",
            "Registry",
            "P2",
            "list_atoms 搜索",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "命中 name/id/alias",
            "",
        ),
        (
            "TC-REG-011",
            "Registry",
            "P1",
            "审计日志完整性",
            "2",
            "提交+审核+流转",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "submit/review/status_change 齐全",
            "",
        ),
        (
            "TC-REG-012",
            "Registry",
            "P0",
            "search SQL 注入尝试",
            "2",
            "' OR '1'='1",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "0 行返回，参数化查询生效",
            "",
        ),
        (
            "TC-REG-013",
            "Registry",
            "P1",
            "submit 缺 atom_id",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "ValueError 提示正确",
            "",
        ),
        (
            "TC-REG-014",
            "Registry",
            "P2",
            "rejected 重新提交",
            "2",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "记录：rejected→submitted 流转符合预期",
            "",
        ),
        (
            "TC-REG-015",
            "Registry",
            "P2",
            "deprecated→registered 回滚",
            "2",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "允许回滚",
            "",
        ),
    ],
    "security": [
        (
            "TC-SEC-001",
            "Security",
            "P0",
            "路径穿越/任意文件读取",
            "3",
            "atom-file-read handler",
            "Completed",
            "Fail",
            "BUG-007",
            DATE,
            WHO,
            "成功读取 C:/Windows/System32/drivers/etc/hosts，无沙箱/白名单（A01）",
            "",
        ),
        (
            "TC-SEC-002",
            "Security",
            "P0",
            "SSRF 内网/回环访问",
            "3",
            "本地回环靶机",
            "Completed",
            "Fail",
            "BUG-008",
            DATE,
            WHO,
            "成功抓取 127.0.0.1 内部服务标记 INTERNAL-SECRET；无协议与地址过滤（A10）",
            "",
        ),
        (
            "TC-SEC-003",
            "Security",
            "P1",
            "0.0.0.0 绑定且无认证",
            "2",
            "静态检查",
            "Completed",
            "Fail",
            "BUG-009",
            DATE,
            WHO,
            "5 原子+模板默认均 0.0.0.0，/run 无任何鉴权（A05/A07）",
            "",
        ),
        (
            "TC-SEC-004",
            "Security",
            "P2",
            "请求体无大小限制",
            "2",
            "静态检查 _read_body",
            "Completed",
            "Fail",
            "BUG-010",
            DATE,
            WHO,
            "Content-Length 无上限，可致内存 DoS（A04）",
            "",
        ),
        (
            "TC-SEC-005",
            "Security",
            "P0",
            "SQL 注入（注册中心）",
            "3",
            "search/category/DROP",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "参数化查询生效，表完好（A03 已缓解）",
            "",
        ),
        (
            "TC-SEC-006",
            "Security",
            "P1",
            "YAML 反序列化安全",
            "1",
            "静态检查",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "meta.py/server.py/sync 全部 yaml.safe_load（A08 已缓解）",
            "",
        ),
        (
            "TC-SEC-007",
            "Security",
            "P1",
            "敏感信息硬编码",
            "3",
            "全仓 grep（已排除 .venv）",
            "Completed",
            "Fail",
            "BUG-011",
            DATE,
            WHO,
            "无密钥入库（Yuanzi-Token 仅 header 名）；但 yuanzi-config.yaml 提交个人 adb 路径；Android token 明文 SharedPreferences+HTTP 明文（A02/A05）",
            "",
        ),
        (
            "TC-SEC-008",
            "Security",
            "P2",
            "错误信息泄露",
            "2",
            "静态检查",
            "Completed",
            "Fail",
            "BUG-012",
            DATE,
            WHO,
            "str(exc)/str(e) 原样回传客户端，可泄露内部路径/结构（A05）",
            "",
        ),
        (
            "TC-SEC-009",
            "Security",
            "P2",
            "依赖供应链锁定",
            "1",
            "pyproject 检查",
            "Completed",
            "Fail",
            "BUG-013",
            DATE,
            WHO,
            "依赖均为 >= 无上限且无 lock 文件（A06）",
            "",
        ),
        (
            "TC-SEC-010",
            "Security",
            "P3",
            "日志与审计",
            "2",
            "静态检查",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "注册中心审计完整（actor/时间戳/状态变迁）；atoms 无访问日志（建议项）（A09）",
            "",
        ),
    ],
    "cli": [
        (
            "TC-CLI-001",
            "CLI",
            "P2",
            "--version 显示版本号",
            "1",
            "venv 安装 yuanzi-cli",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "输出 yuanzi-cli 0.1.0",
            "",
        ),
        (
            "TC-CLI-002",
            "CLI",
            "P0",
            "init 默认模板生成原子",
            "3",
            "无",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "默认模板解析正常，6 个关键文件齐全",
            "",
        ),
        (
            "TC-CLI-003",
            "CLI",
            "P0",
            "init 产物可通过 validate",
            "2",
            "TC-CLI-002",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "OK: com.qa.demo@0.1.0",
            "",
        ),
        (
            "TC-CLI-004",
            "CLI",
            "P1",
            "init 拒绝非法 atom_id",
            "2",
            "无",
            "Completed",
            "Fail",
            "BUG-001",
            DATE,
            WHO,
            "非法 id 'BAD ID!!' 仍生成目录，exit=0",
            "",
        ),
        (
            "TC-CLI-005",
            "CLI",
            "P2",
            "init 目标目录已存在",
            "2",
            "先 init 一次",
            "Completed",
            "Fail",
            "BUG-002",
            DATE,
            WHO,
            "抛出未处理 OutputDirExistsException（traceback）",
            "",
        ),
        (
            "TC-CLI-006",
            "CLI",
            "P0",
            "validate 官方示例原子",
            "1",
            "无",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "com.example.sum@0.1.0",
            "",
        ),
        (
            "TC-CLI-007",
            "CLI",
            "P1",
            "validate 缺 meta.yaml",
            "1",
            "空目录",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "exit=1，提示 meta.yaml not found",
            "",
        ),
        (
            "TC-CLI-008",
            "CLI",
            "P1",
            "validate 缺必需文件",
            "2",
            "删除 test_health.py",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "准确列出缺失文件",
            "",
        ),
        (
            "TC-CLI-009",
            "CLI",
            "P1",
            "validate 非法 meta",
            "1",
            "bad-id",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "validation failed 提示清晰",
            "",
        ),
        (
            "TC-CLI-010",
            "CLI",
            "P2",
            "markdown_rules 缺 rules.md",
            "2",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "正确要求 rules.md",
            "",
        ),
        (
            "TC-CLI-011",
            "CLI",
            "P2",
            "meta.yaml 为列表",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "exit=1，可读错误，无 traceback",
            "",
        ),
        (
            "TC-CLI-012",
            "CLI",
            "P0",
            "test 命令完整流程",
            "3",
            "com.example.sum",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "validate OK + 8 passed，rc=0（子进程验证）",
            "",
        ),
        (
            "TC-CLI-013",
            "CLI",
            "P1",
            "test --fast 只跑 kernel",
            "2",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "fast mode，5 passed（health 3 条被跳过）",
            "",
        ),
        (
            "TC-CLI-014",
            "CLI",
            "P2",
            "test --no-validate",
            "2",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "跳过 validate，8 passed",
            "",
        ),
        (
            "TC-CLI-015",
            "CLI",
            "P1",
            "test 失败套件返回非零",
            "3",
            "植入错误逻辑",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "rc=1，pytest 报 failed",
            "",
        ),
        (
            "TC-CLI-016",
            "CLI",
            "P2",
            "meta id 校验边界",
            "2",
            "直接调 validate_meta",
            "Completed",
            "Pass",
            "BUG-003",
            DATE,
            WHO,
            "空格被拒（正确）；但大写与中文 id 被接受，与反向域名规范不符",
            "",
        ),
        (
            "TC-CLI-017",
            "CLI",
            "P2",
            "meta port 边界",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "0/65536 拒绝，18777 通过",
            "",
        ),
        (
            "TC-CLI-018",
            "CLI",
            "P2",
            "init 自定义 template-dir",
            "2",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "-t 参数正常",
            "",
        ),
        (
            "TC-CLI-019",
            "CLI",
            "P3",
            "无参数显示帮助",
            "1",
            "",
            "Completed",
            "Pass",
            "",
            DATE,
            WHO,
            "显示 usage；注意 exit=2（Typer 惯例，可接受）",
            "",
        ),
        (
            "TC-CLI-020",
            "CLI",
            "P1",
            "相对路径测试 CWD 健壮性",
            "3",
            "从仓库根跑 pytest",
            "Completed",
            "Pass",
            "BUG-004",
            DATE,
            WHO,
            "exit=0 但系巧合：../yuanzi-atom-templates 解析到仓库外的另一副本（内容不一致），存在假阳性风险",
            "",
        ),
    ],
}


def main():
    cat = sys.argv[1]
    rows = ROWS[cat]
    exists = CSV.exists()
    existing = []
    if exists:
        with open(CSV, newline="", encoding="utf-8") as f:
            existing = list(csv.reader(f))
    # drop example row if present
    body = (
        [r for r in existing[1:] if r and not r[0].startswith("TC-001")]
        if existing
        else []
    )
    body.extend([list(r) for r in rows])
    with open(CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(HEADER)
        w.writerows(body)
    print(f"wrote {len(rows)} rows for {cat}; total rows now {len(body)}")


if __name__ == "__main__":
    main()
