"""Write BUG-TRACKING-TEMPLATE.csv with all confirmed defects."""

from __future__ import annotations

import csv
from pathlib import Path

CSV = (
    Path(__file__).resolve().parents[1]
    / "docs"
    / "templates"
    / "BUG-TRACKING-TEMPLATE.csv"
)
DATE = "2026-07-18"
ENV = "OS: Windows 11\nPython: 3.12.13\nyuanzi-cli: 0.1.0\nRepo: main@7205ebe"

HEADER = [
    "Bug ID",
    "Title",
    "Severity",
    "Component",
    "Test Case ID",
    "Status",
    "Reported Date",
    "Reported By",
    "Assigned To",
    "Description",
    "Steps to Reproduce",
    "Expected Result",
    "Actual Result",
    "Environment",
    "Screenshots/Logs",
    "Resolution",
    "Resolved Date",
    "Verified By",
    "Verification Date",
]

BUGS = [
    (
        "BUG-001",
        "yuanzi init 不校验 atom_id，非法 id 也可生成原子",
        "P1",
        "yuanzi-cli / init",
        "TC-CLI-004",
        "Open",
        DATE,
        "Kimi-QA",
        "CLI 维护者",
        "init 命令把 atom_id 原样传给 cookiecutter，不复用 meta.py 中已有的 validate_atom_id 校验。非法 id（含空格、特殊字符）会生成非法目录，直到 validate 阶段才报错，且目录名本身可能不合法。",
        '1. yuanzi init "BAD ID!!" --output-dir <tmp>',
        "退出码非 0，提示 atom_id 非法，不生成目录",
        "exit=0，成功生成目录 'BAD ID!!'",
        ENV,
        "",
        "init 中复用 yuanzi_cli.meta.validate_meta 的 id 校验，非法时 typer.Exit(1)",
        "",
        "",
        "",
    ),
    (
        "BUG-002",
        "yuanzi init 目标目录已存在时抛出未处理异常（traceback）",
        "P2",
        "yuanzi-cli / init",
        "TC-CLI-005",
        "Open",
        DATE,
        "Kimi-QA",
        "CLI 维护者",
        "重复 init 同一 atom_id 时，cookiecutter 抛 OutputDirExistsException，CLI 未捕获，用户看到 Python traceback。",
        "1. yuanzi init com.qa.dup -o <tmp>\n2. 再次执行同一命令",
        "清晰错误提示（目录已存在），或提供 --overwrite 选项",
        "OutputDirExistsException traceback，exit=1",
        ENV,
        "",
        "捕获 cookiecutter 异常并转为友好提示；可选增加 --overwrite-if-exists 参数",
        "",
        "",
        "",
    ),
    (
        "BUG-003",
        "meta id 校验过宽：接受大写字母与中文字符",
        "P3",
        "yuanzi-cli / meta.py",
        "TC-CLI-016",
        "Open",
        DATE,
        "Kimi-QA",
        "CLI 维护者",
        "validate_atom_id 使用 str.isalnum()，对中文返回 True，对大写也放行。'com.中文.x' 与 'COM.EXAMPLE.X' 均通过校验，与反向域名（DNS 风格小写）惯例不符，后续注册/检索可能不一致。",
        "1. 调用 validate_meta(id='com.中文.x')\n2. 调用 validate_meta(id='COM.EXAMPLE.X')",
        "仅接受小写字母数字与 -_（如正则 ^[a-z0-9][a-z0-9_-]*(\\.[a-z0-9][a-z0-9_-]*)+$）",
        "两者均被接受",
        ENV,
        "",
        "将 isalnum 改为显式 ASCII 小写字符集校验",
        "",
        "",
        "",
    ),
    (
        "BUG-004",
        "test_validate.py 相对路径依赖 CWD，存在假阳性风险",
        "P2",
        "yuanzi-cli / tests",
        "TC-CLI-020",
        "Open",
        DATE,
        "Kimi-QA",
        "CLI 维护者",
        "test_validate_example_sum 使用相对路径 '../yuanzi-atom-templates/examples/com.example.sum'，只在 CWD=yuanzi-cli 时指向仓库内示例。从仓库根目录运行时解析到仓库外路径；本机实测恰好命中 workspace 下另一份内容不同的副本，测试'通过'但验证的是错误文件（假阳性）。",
        "1. cd <repo 根>\n2. pytest yuanzi-cli/tests",
        "使用 Path(__file__).resolve() 锚定路径（如 test_init.py 的写法），任何 CWD 下都测同一份文件",
        "结果依赖运行目录；实测在根目录误测了内容不一致的外部副本",
        ENV,
        "",
        "改用 Path(__file__).resolve().parents[N] / 'yuanzi-atom-templates/...'",
        "",
        "",
        "",
    ),
    (
        "BUG-005",
        "5 个示例原子全部硬编码 0.0.0.0:8080，无法同时启动",
        "P1",
        "atoms / server.py",
        "TC-ATM-017",
        "Open",
        DATE,
        "Kimi-QA",
        "原子维护者",
        "atom-file-read / http-get / math-sum / string-split / template 的 server.py 均 app.run(host='0.0.0.0', port=8080)。端口冲突导致同机只能运行一个；与 yuanzi-config.yaml 的 default_port_range [9000,9100] 设计不符。",
        "1. 静态检查 atoms/*/server.py 的 app.run 端口",
        "端口从 meta.yaml/环境变量读取，或各自不同且在默认端口段内",
        "全部 8080，互相冲突",
        ENV,
        "",
        "server.py 读取 meta.yaml runtime.port 或 PORT 环境变量；示例分配不同端口",
        "",
        "",
        "",
    ),
    (
        "BUG-006",
        "注册中心去重签名包含 atom_id，能力去重失效",
        "P1",
        "mcp-yuanzi-bridge / registry.py",
        "TC-REG-002",
        "Open",
        DATE,
        "Kimi-QA",
        "注册中心维护者",
        "compute_signature 的签名载荷包含 atom_id。两个能力完全相同但 atom_id 不同的原子签名必然不同，submit_atom 中 '同 signature 被其他 atom_id 占用' 的 duplicate_signature 检查成为死代码，无法拦截重复能力注册（与其设计意图和错误信息矛盾）。",
        "1. submit atom A(atom_id=com.qa.alpha, functions=[f1])\n2. submit atom B(atom_id=com.qa.beta, functions=[f1], 其余相同)",
        "B 被拒绝，error=duplicate_signature",
        "B 注册成功（success=True）",
        ENV,
        "",
        "从签名载荷中移除 atom_id（或拆分为身份签名与能力签名两套）",
        "",
        "",
        "",
    ),
    (
        "BUG-007",
        "atom-file-read 可读取系统任意文件（无沙箱）",
        "P0",
        "atoms / atom-file-read",
        "TC-SEC-001",
        "Open",
        DATE,
        "Kimi-QA",
        "原子维护者",
        "core.py 对 path 不做任何限制/白名单/根目录约束。任何可访问 /run 的调用方可读取进程权限内的任意文件（如 C:/Windows/System32/drivers/etc/hosts、私钥、配置），属于 OWASP A01 访问控制失效。",
        "1. handler({'path': 'C:/Windows/System32/drivers/etc/hosts'})",
        "拒绝沙箱外路径（如仅允许配置的白名单根目录）",
        "status=success，返回系统文件内容",
        ENV,
        "",
        "增加允许根目录配置 + 路径规范化校验（realpath 前缀检查）；拒绝 .. 穿越",
        "",
        "",
        "",
    ),
    (
        "BUG-008",
        "atom-http-get 存在 SSRF：可访问内网/回环任意地址",
        "P0",
        "atoms / atom-http-get",
        "TC-SEC-002",
        "Open",
        DATE,
        "Kimi-QA",
        "原子维护者",
        "core.py 对 url 无协议白名单与内网地址过滤。实测可抓取 127.0.0.1 上'内部服务'的响应内容。云/内网元数据服务（如 169.254.169.254）同样可达，属于 OWASP A10 SSRF。",
        "1. 在 127.0.0.1 起本地服务返回 INTERNAL-SECRET\n2. handler({'url': 'http://127.0.0.1:<port>/internal'})",
        "仅允许 http/https + 公网地址（或显式白名单），拒绝 RFC1918/回环/链路本地地址",
        "status=success，内部内容泄露",
        ENV,
        "",
        "协议白名单 + 解析后 IP 过滤（拒绝私网/回环），可选出站代理",
        "",
        "",
        "",
    ),
    (
        "BUG-009",
        "原子服务绑定 0.0.0.0 且 /run 无任何鉴权",
        "P1",
        "atoms + 模板 server.py",
        "TC-SEC-003",
        "Open",
        DATE,
        "Kimi-QA",
        "原子维护者",
        "5 个示例原子与模板 server.py 默认均绑定 0.0.0.0，/run 端点无 token/签名/来源校验。在局域网中任何主机都可调用原子能力（配合 BUG-007/008 可远程读文件/打内网）。模板 meta.yaml 也写死 host: 0.0.0.0。",
        "1. 检查 atoms/*/server.py app.run host\n2. 检查模板 server.py HOST 默认值与鉴权逻辑",
        "默认绑定 127.0.0.1；对外暴露时强制认证（如 Yuanzi-Token 校验）",
        "0.0.0.0 + 无认证",
        ENV,
        "",
        "默认 127.0.0.1；模板加入可选 token 中间件；文档说明对外暴露的加固步骤",
        "",
        "",
        "",
    ),
    (
        "BUG-010",
        "模板 server 请求体无大小限制（内存 DoS）",
        "P2",
        "yuanzi-atom-templates / server.py",
        "TC-SEC-004",
        "Open",
        DATE,
        "Kimi-QA",
        "模板维护者",
        "_read_body 直接按 Content-Length 读取，无上限校验。恶意客户端可声明超大长度耗尽内存（OWASP A04 不安全设计）。",
        "1. 检查模板 server.py _read_body",
        "限制最大 body（如 1-5MB），超限返回 413",
        "无上限读取",
        ENV,
        "",
        "增加 MAX_BODY_BYTES 常量并在读取前校验",
        "",
        "",
        "",
    ),
    (
        "BUG-011",
        "yuanzi-config.yaml 提交个人机器路径；Android token 明文存储+HTTP 明文传输",
        "P3",
        "配置 / widgetmcp_src",
        "TC-SEC-007",
        "Open",
        DATE,
        "Kimi-QA",
        "配置维护者",
        "1) yuanzi-config.yaml 的 sync.adb_path 写死个人目录 'C:/aaaaa/Tsumugi的解锁小工具v2.9（完整版）...'，含中文且为他人不可用的机器特定路径；2) Android 端 token 存于普通 SharedPreferences（明文），且 baseUrl 为 http:// 明文传输（局域网下 token 可被嗅探）。未发现硬编码密钥（Yuanzi-Token 仅为 header 名）。",
        "1. 查看 yuanzi-config.yaml sync.adb_path\n2. 查看 YuanziConfig.kt token 存储与 baseUrl",
        "adb 路径默认 'adb' 或读取本地未跟踪配置文件（如 yuanzi-config.local.yaml）；token 使用 EncryptedSharedPreferences；文档建议仅回环/可信网络或上 HTTPS",
        "个人路径入库；token 明文存储+明文传输",
        ENV,
        "",
        "拆分本地配置文件并加入 .gitignore；移动端改用 EncryptedSharedPreferences",
        "",
        "",
        "",
    ),
    (
        "BUG-012",
        "内部异常详情原样回传客户端",
        "P2",
        "模板 server.py + atoms core.py",
        "TC-SEC-008",
        "Open",
        DATE,
        "Kimi-QA",
        "模板维护者",
        "模板 do_POST 异常时返回 {'ok': False, 'error': str(exc)}；atoms core.py 同样回传 str(e)。异常文本可能包含文件系统路径、SQL 片段、库版本等内部信息（OWASP A05）。",
        "1. 检查模板 server.py 异常分支\n2. 触发一次内核异常观察响应",
        "对外返回通用错误码/消息，详细异常仅记录服务端日志",
        "str(exc) 原样出现在 HTTP 响应",
        ENV,
        "",
        "生产模式返回通用错误；debug 模式才回传详情；异常进日志",
        "",
        "",
        "",
    ),
    (
        "BUG-013",
        "Python 依赖未锁定（>= 无上限，无 lock 文件）",
        "P3",
        "构建 / pyproject.toml",
        "TC-SEC-009",
        "Open",
        DATE,
        "Kimi-QA",
        "工程效能",
        "yuanzi-cli 依赖全部为 >= 范围（cookiecutter/pydantic/pyyaml/requests/typer 等），仓库无 lock 文件。无法保证可复现构建，上游次版本可能引入破坏性变更或已知漏洞（OWASP A06）。",
        "1. 查看 yuanzi-cli/pyproject.toml dependencies\n2. 检查仓库根有无 lock 文件",
        "提供 lock（如 uv.lock/requirements.lock）或至少上限约束；CI 定期扫描漏洞",
        "无锁定，无漏洞扫描",
        ENV,
        "",
        "引入 uv/pip-tools 生成 lock；CI 接入 pip-audit",
        "",
        "",
        "",
    ),
]


def main():
    with open(CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(HEADER)
        w.writerows(BUGS)
    print(f"wrote {len(BUGS)} bugs -> {CSV}")


if __name__ == "__main__":
    main()
